default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 3 } %>
  timeout: 5000
  port: 5439

development:
  <<: *default
  adapter: redshift
  database: ganalytic
  username: root
  password: Haha123.
  host: ganalytic.cvqb8lx7aald.us-west-2.redshift.amazonaws.com

production:
  <<: *default
  adapter: redshift
  database: ganalytic
  username: root
  password: Haha123.
  host: ganalytic.cvqb8lx7aald.us-west-2.redshift.amazonaws.com